---
namespace: ansible
name: receptor
version: 2.0.3
readme: README.md
authors:
  - Ansible
description: Receptor installer
license_file: LICENSE
tags:
  - networking
  - infrastructure
  - receptor
repository: https://github.com/ansible/receptor-collection
