---
- name: Include OS-specific variables "{{ ansible_os_family }}"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family in ['RedHat', 'Debian']

- name: Define podman_packages
  ansible.builtin.set_fact:
    podman_packages: "{{ __podman_packages | list }}"
  when: podman_packages is not defined
