---
- name: Create receptor config dir
  ansible.builtin.file:
    path: "{{ receptor_config_dir }}"
    state: directory
    owner: "{{ receptor_user }}"
    group: "{{ receptor_group }}"
    mode: '0750'

- name: Deploy receptor config
  ansible.builtin.template:
    src: templates/receptor.conf.j2
    dest: "{{ receptor_config_dir }}/receptor.conf"
    mode: '0644'
    owner: "{{ receptor_user }}"
    group: "{{ receptor_group }}"
  notify:
    - Reload Receptor
