---
- name: Deploy receptor config
  ansible.builtin.template:
    src: templates/receptor.conf.j2
    dest: "{{ receptor_config_path }}/receptor.conf"
    mode: '0644'
    owner: "{{ receptor_user }}"
    group: "{{ receptor_group }}"
  # notify:
  #   - "Receptor Reload"
