---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: configure.yml

- name: Start Receptor service
  systemd:
    name: receptor
    state: started
    daemon_reload: yes
    enabled: yes
