---
- name: Run preflight
  ansible.builtin.include_tasks: preflight.yml

# Variable configuration.
- name: Include variables
  ansible.builtin.include_tasks: variables.yml

# Setup/install tasks.
- name: Run OS-specific tasks
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']

- name: Append receptorctl to python packages if needed
  ansible.builtin.set_fact:
    additional_python_packages: "{{ additional_python_packages + ['receptorctl'] }}"
  when:
    - receptor_install_method in ['release', 'local']
    - "'receptorctl' not in additional_python_packages"

- name: Install python packages
  ansible.builtin.include_tasks: python_packages.yml
  when: additional_python_packages | length > 0

- name: Receptor install local
  ansible.builtin.include_tasks: setup-local.yml
  when: receptor_install_method == 'local'

- name: Receptor install release
  ansible.builtin.include_tasks: setup-release.yml
  when: receptor_install_method == 'release'

- name: Check if receptor was installed correctly
  when: receptor_install_method in ['release', 'local', 'package']
  ansible.builtin.command: "receptor --version"
  changed_when: false
  register: receptor_version
  ignore_errors: true

- name: Assert receptor installation
  when: receptor_install_method in ['release', 'local', 'package']
  ansible.builtin.assert:
    that:
      - receptor_version.rc == 0
    fail_msg: "Receptor not installed correctly. Please check the installation or reinstall it with local_receptor: true"
    success_msg: "Receptor installed correctly"

- name: Configure receptor socket
  ansible.builtin.include_tasks: configure.yml

- name: TLS files
  ansible.builtin.include_tasks: tls.yml
  when: receptor_tls

- name: Work signing
  ansible.builtin.include_tasks: worksign.yml
  when: receptor_sign or receptor_verify

- name: Generate receptor config
  ansible.builtin.include_tasks: generate_config.yml

- name: Receptor install container
  ansible.builtin.include_tasks: setup-container.yml
  when: receptor_install_method == 'container'

- name: Setup systemd
  ansible.builtin.include_tasks: setup-service.yml
  when: receptor_install_method in ['release', 'local', 'package']

- name: Start Receptor service
  when: receptor_install_method in ['release', 'local', 'package']
  ansible.builtin.systemd:
    name: "{{ receptor_service_name }}"
    state: started
    daemon_reload: true
    enabled: true
  register: _started
