---
- include_tasks: preflight.yml

# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']

- include_tasks: "setup-local.yml"
  when: receptor_install_method == 'local'

- include_tasks: "setup-release.yml"
  when: receptor_install_method == 'release'

- name: Check if receptor was installed correctly
  ansible.builtin.command: "receptor --version"
  register: receptor_version
  changed_when: receptor_version.rc == 0
  ignore_errors: true

- name: Assert receptor installation
  ansible.builtin.assert:
    that:
      - receptor_version.rc == 0
    fail_msg: "Receptor not installed correctly. Please check the installation or reinstall it with local_receptor: true"
    success_msg: "Receptor installed correctly"

- name: Install receptorctl
  block:
    - name: Install receptorctl via pip
      ansible.builtin.pip:
        name: receptorctl

    - name: Symlink receptorctl to /usr/bin
      ansible.builtin.file:
        state: link
        src: /usr/local/bin/receptorctl
        dest: /usr/bin/receptorctl
  when: receptor_install_method != 'package'

- include_tasks: configure.yml

- include_tasks: tls.yml
  when: receptor_tls

- include_tasks: worksign.yml
  when: receptor_sign or receptor_verify

- include_tasks: generate_config.yml

- include_tasks: "setup-service.yml"
  when: receptor_install_method in ['release', 'local']

- name: Start Receptor service
  ansible.builtin.systemd:
    name: "{{ receptor_service_name }}"
    state: started
    daemon_reload: true
    enabled: true
  register: _started
