---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian'] and not local_receptor

- include_tasks: "setup-local.yml"
  when: local_receptor

- name: Check if receptor was installed correctly
  ansible.builtin.command: "receptor --version"
  register: receptor_version
  changed_when: receptor_version.rc == 0
  ignore_errors: true

- name: Assert receptor installation
  ansible.builtin.assert:
    that:
      - receptor_version.rc == 0
    fail_msg: "Receptor not installed correctly. Please check the installation or reinstall it with local_receptor: true"
    success_msg: "Receptor installed correctly"

- include_tasks: configure.yml

- include_tasks: tls.yml
  when: receptor_tls

- include_tasks: worksign.yml
  when: receptor_sign or receptor_verify

- name: Deploy receptor config
  ansible.builtin.template:
    src: templates/receptor.conf.j2
    dest: "{{ receptor_config_path }}/receptor.conf"
    mode: '0644'
    owner: "{{ receptor_user }}"
    group: "{{ receptor_group }}"
  # notify:
  #   - "Receptor Reload"

- name: Start Receptor service
  ansible.builtin.systemd:
    name: "{{ receptor_service_name }}"
    state: restarted
    daemon_reload: true
    enabled: true
