---
- name: Pull the latest relase of receptor from Quay
  containers.podman.podman_image:
    name: quay.io/ansible/receptor
    tag: latest
    state: present

- name: Run receptor image
  containers.podman.podman_container:
    name: receptor
    image: quay.io/ansible/receptor
    state: started
    volume:
      - "{{ receptor_config_dir }}/receptor.conf:/etc/receptor/receptor.conf:Z"
    generate_systemd:
      container_prefix: ''
      path: /etc/systemd/system
      separator: ''
