---
- name: Install receptor packages
  ansible.builtin.apt:
    name: "{{ receptor_packages }}"
    state: present
  when: not local_receptor

- name: Install dependencies specific to the node type
  ansible.builtin.apt:
    name: "{{ receptor_dependencies | default([]) }}"
    state: present
