---
name: SonarCloud Analysis

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Run ansible-lint
        run: |
          mkdir -p reports
          ansible-lint -f sarif roles/ > reports/ansible-lint.sarif
        continue-on-error: true

      - name: SonarCloud Scan (on push to main)
        uses: SonarSource/sonarqube-scan-action@v6
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          SONAR_TOKEN: ${{ secrets[format('{0}', vars.SONAR_TOKEN_SECRET_NAME)] }}

      - name: SonarCloud Scan (on PR)
        uses: SonarSource/sonarqube-scan-action@v6
        if: github.event_name == 'pull_request'
        env:
          SONAR_TOKEN: ${{ secrets[format('{0}', vars.SONAR_TOKEN_SECRET_NAME)] }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
